### PR TITLE
✨ (app-icon): create app icon displayed on Expo App

### PR DESCRIPTION
**Pull request by nilvng**

### CODE REVIEW

**Review by thesupersonic16 — CHANGES_REQUESTED** [review]
Can you make sure if the old two PNG are still necessary?

**Comment by nilvng** [comment]
@thesupersonic16 you mean if we use it anywhere else? and we should replace it?

**Comment by thesupersonic16** [comment]
> @thesupersonic16 you mean if we use it anywhere else? and we should replace it?

We should remove it if it is not in use anymore.

**Comment by nilvng** [comment]
> We should remove it if it is not in use anymore.

Request resolved!

**Review by thesupersonic16 — APPROVED** [review]
LGTM

**Pull request merged**
