### PR TITLE
💄  (symposium-receive): Add view when a symposium is live 

### PR DESCRIPTION
**Pull request by thesupersonic16**
boop

### CODE REVIEW

**Comment by nilvng** [comment]
Any idea why I encounter this error when build the app? @thesupersonic16

**Comment by thesupersonic16** [comment]
I am not really sure what that error means. Does th error still occur when you have all the packages installed but without the js view file?

**Comment by nilvng** [comment]
yea, so I followed this[ instructions](https://stackoverflow.com/questions/58771086/error-while-updating-property-fontsize-in-shadow-node-of-type-rcttext): remove node_modules, clean cache, and install again. but the error persists

**Comment by thesupersonic16** [comment]
Might be possible some Expo platforms other than web does not like the size units I was using.

**Review by nilvng — APPROVED** [review]
🚢

**Pull request merged**
